version: 0.1.{build}
image: Visual Studio 2017
configuration: Release

build_script:
  - cmd: dotnet build -c Release

deploy:
- provider: GitHub
  release: NPC-Attack-v$(appveyor_build_version)
  description: main dll
  auth_token:
    secure: 'BZhxXnJJTrPVahMCJMt/lttcFJ/aLonezD6Ge7A4vAdhbHjB8VUMwldMIhFlVDrS'
  artifact: NPCAttack\bin\Release\NPCAttack.dll
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
