image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build_script:
  - cmd: dotnet build -c Release

artifacts:
  - path: NPCAttack\bin\Release\NPCAttack.dll
    name: extension

deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: NPCAttack v$(appveyor_repo_tag_name)
  artifacts: extension
  auth_token:
    secure: 'BZhxXnJJTrPVahMCJMt/lttcFJ/aLonezD6Ge7A4vAdhbHjB8VUMwldMIhFlVDrS'
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
